server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: running_app_backend
  
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:15432}/runningMate
    username: ${DB_USERNAME:running}
    password: ${DB_PASSWORD}
    initialization:
      enabled: true
  sql:
    init:
      mode: always

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
